# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caxJLsbK52y1k2sJRW3A1OcTW6bF48v_
"""

def add(x, y):
    return x + y

print(add(1, 2))

def subtract(x, y):
    return x - y

print(subtract(3, 2))

def multiply(x, y):
    return x * y

print(multiply(2, 3))

def divide(x, y):
    return x / y

print (divide(4, 2))

def square(x):
    return x^3

print(square(2))

def power(x, y):
    return x**y

print (power(2, 2))

import math
def SquareRoot(x):
    return math.sqrt(x)

print(SquareRoot(4))